<a href="https://colab.research.google.com/github/RSeth-Creator/Data/blob/dataScience/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np 

# **Array Operation**

In [3]:
#Python array 
from array import array as arr
a  = arr('i',[1,2,3,4])
a

array('i', [1, 2, 3, 4])

In [4]:
# numpy array
np.array([1,2,3,4,5])
print(np.array([1,2,3]))

[1 2 3]


In [5]:
#Numpy array with external data type
np.array([1,2,3,4],dtype=float)

array([1., 2., 3., 4.])

In [6]:
#Array with for loop
l=[1,2,3,4]
s = np.array([i+3 for i in l ],dtype=float).reshape(2,2)
s

array([[4., 5.],
       [6., 7.]])

In [7]:
#Array with for loop
s = np.array([range(i,i+3) for i in l])
print(s)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]


In [8]:
#Matrix operations
np.full((3,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [9]:
#Identity matrix
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
#series with specific interval 
np.arange(0,10,3)

array([0, 3, 6, 9])

In [11]:
#Series with partition
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [12]:
#random function
np.random.random((3,3))

array([[0.71702681, 0.70712665, 0.89071126],
       [0.93531498, 0.71912895, 0.5727561 ],
       [0.73217482, 0.39700402, 0.14897267]])

In [13]:
#ranint
np.random.randint(0,9,(3,3))

array([[0, 5, 2],
       [8, 7, 4],
       [6, 3, 6]])

In [14]:
# Normal distribution
np.random.normal(0,1,(3,3))

array([[-0.48291376,  1.056894  , -0.03752433],
       [ 0.55123304, -0.34019727,  0.95027895],
       [ 1.03483698,  0.43446121,  0.68182717]])

In [15]:
#One dimensional array
np.random.randint(10,size=10)

array([8, 5, 1, 7, 4, 5, 5, 9, 5, 6])

In [16]:
#Two Dimensional array
np.random.randint(10,size=(3,3))

array([[8, 4, 9],
       [7, 4, 3],
       [8, 9, 3]])

In [17]:
#3dimensional array 
np.random.randint(10,size=(3,3,3))

array([[[9, 8, 0],
        [1, 4, 0],
        [2, 3, 6]],

       [[5, 2, 4],
        [3, 5, 2],
        [1, 7, 2]],

       [[9, 4, 1],
        [2, 5, 3],
        [4, 9, 0]]])

In [18]:
#Slicing
x = np.random.randint(100,size=(10))
x

array([ 6, 39, 77, 53, 44, 44, 96, 46, 22,  3])

In [19]:
#last element
x[-1]

3

In [20]:
#Reverse an array 
x[-1::-1]

array([ 3, 22, 46, 96, 44, 44, 53, 77, 39,  6])

In [21]:
#Slicing an array nyusing index
x[1:4]

array([39, 77, 53])

In [22]:
x[::-2]

array([ 3, 46, 44, 53, 39])

In [23]:
x[4:8]

array([44, 44, 96, 46])

In [24]:
y = np.random.randint(100,size=(3,3))
y

array([[ 2, 55, 93],
       [51, 88,  1],
       [28, 64, 66]])

# **Slicing,Concatenation and splitting Operation in Array**

In [25]:
y[1:3]

array([[51, 88,  1],
       [28, 64, 66]])

In [26]:
y[:3,:2]

array([[ 2, 55],
       [51, 88],
       [28, 64]])

In [27]:
#Reverse
y[::-1,::-1]

array([[66, 64, 28],
       [ 1, 88, 51],
       [93, 55,  2]])

In [28]:
y1 = x[::-2].copy()
y1

array([ 3, 46, 44, 53, 39])

In [29]:
x1 = np.random.randint(100,size=(12))

In [30]:
#Copy of a result
x1_copy = x1.reshape(3,4).copy()

In [31]:
#reshaping a n dimensional array
x1_copy.reshape(3,2,2)

array([[[14, 30],
        [84, 97]],

       [[ 1, 90],
        [12, 30]],

       [[90, 76],
        [75, 72]]])

In [32]:
c1 = np.array([1,2,3])
c2 = np.array([[2,3,4],[3,4,5]])
c3 = np.random.randint(100,size=(3,3))
c4 = np.array([[1],[2],[3]])

In [33]:
#Concatenation of two equal dimensional array
np.concatenate([c2,c2])

array([[2, 3, 4],
       [3, 4, 5],
       [2, 3, 4],
       [3, 4, 5]])

In [34]:
#Vertical stacking 
np.vstack([c1,c2])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [35]:
#Horizontal stack
np.hstack([c4,c3])

array([[ 1, 16, 13, 83],
       [ 2, 37, 43,  1],
       [ 3, 54,  6, 91]])

In [36]:
#Vertical split
np.vsplit(c2,[2])

[array([[2, 3, 4],
        [3, 4, 5]]), array([], shape=(0, 3), dtype=int64)]

In [37]:
#Horizontal split
np.hsplit(c2,(1,2))

[array([[2],
        [3]]), array([[3],
        [4]]), array([[4],
        [5]])]

In [38]:
#Split an existing n dimesional array
np.split(x,(4,4))

[array([ 6, 39, 77, 53]),
 array([], dtype=int64),
 array([44, 44, 96, 46, 22,  3])]

**Array arithmetic**

In [39]:
#(no of element for both array should be same)
np.arange(1,10,2)/np.arange(2,15,3)

array([0.5       , 0.6       , 0.625     , 0.63636364, 0.64285714])

# **Matrix operations**




In [40]:
m1= np.random.randint(100,size = 9).reshape(3,3)
print('m1*m1 = ','\n',np.matmul(m1,m1))
print('\n')
print('Invert = ','\n',np.invert(m1))
print('\n')
print('Inverse of m1  = ','\n', np.linalg.inv(m1))
print('\n')
print('Rank of m1 ','\n',np.linalg.matrix_rank(m1))
print('\n')
print('SVD of m1 = ','\n',np.linalg.svd(m1))
print('\n')
print('eigenvalues of m1 = ','\n',np.linalg.eigvals(m1))
print('\n')
print('eigen vectors of m1 is ','\n',np.linalg.eig(m1))

m1*m1 =  
 [[ 6670  8159  4908]
 [ 3861  4779  3018]
 [ 8415 11076  9406]]


Invert =  
 [[-58 -70 -27]
 [-34 -37 -19]
 [-45 -68 -85]]


Inverse of m1  =  
 [[-0.10891445  0.24287084 -0.01833214]
 [ 0.1186197  -0.21830817  0.0100647 ]
 [-0.0375629   0.0469087   0.01347951]]


Rank of m1  
 3


SVD of m1 =  
 (array([[-0.58432801, -0.6781626 , -0.44570873],
       [-0.3315636 , -0.30178673,  0.8938626 ],
       [-0.74069316,  0.67008974, -0.0485116 ]]), array([152.43376707,  40.40546941,   2.71011074]), array([[-0.50407988, -0.6683648 , -0.54698444],
       [-0.47345771, -0.31583666,  0.82224388],
       [ 0.7223166 , -0.67345059,  0.15723557]]))


eigenvalues of m1 =  
 [138.24442012  41.65426655  -2.89868667]


eigen vectors of m1 is  
 (array([138.24442012,  41.65426655,  -2.89868667]), array([[ 0.51681698,  0.49559455,  0.71353289],
       [ 0.30746481,  0.20757605, -0.68117873],
       [ 0.79897784, -0.84338498,  0.16390958]]))


# **Arithmetic Operations **

In [41]:
op = np.random.randint(100,size=(8))
print('addition','\n',np.add(op,3))
print('\n')
print('multiply','\n',np.multiply(op,3))
print('\n')
print('division','\n',np.divide(op,3))
print('\n')
print(' mod_division','\n',np.divmod(op,3))
print('\n')
print(' mod_division','\n',np.subtract(op,3))
print('\n')
print(' square','\n',np.power(op,2))
print('\n')
print(' mod value','\n',np.mod(op,5))
print('\n')
print(' exponential  value','\n',np.exp(op))
print('\n')
print(' 2^op','\n',np.exp2(op))
print('\n')
print(' power series','\n',np.power(3,op))
print('\n')
print(' log','\n',np.log(op))
print('\n')
print(' log2','\n',np.log2(op))
print('\n')
print(' log10','\n',np.log10(op))

addition 
 [26 56 10 76 99 71  3  4]


multiply 
 [ 69 159  21 219 288 204   0   3]


division 
 [ 7.66666667 17.66666667  2.33333333 24.33333333 32.         22.66666667
  0.          0.33333333]


 mod_division 
 (array([ 7, 17,  2, 24, 32, 22,  0,  0]), array([2, 2, 1, 1, 0, 2, 0, 1]))


 mod_division 
 [20 50  4 70 93 65 -3 -2]


 square 
 [ 529 2809   49 5329 9216 4624    0    1]


 mod value 
 [3 3 2 3 1 3 0 1]


 exponential  value 
 [9.74480345e+09 1.04137594e+23 1.09663316e+03 5.05239363e+31
 4.92345829e+41 3.40427605e+29 1.00000000e+00 2.71828183e+00]


 2^op 
 [8.38860800e+06 9.00719925e+15 1.28000000e+02 9.44473297e+21
 7.92281625e+28 2.95147905e+20 1.00000000e+00 2.00000000e+00]


 power series 
 [         94143178827 -2709163618235644365                 2187
  6572658003009201123 -8235400117272609919  6403700247714450769
                    1                    3]


 log 
 [3.13549422 3.97029191 1.94591015 4.29045944 4.56434819 4.21950771
       -inf 0.        ]


 log2 
 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: RuntimeWarning: divide by zero encountered in log
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: RuntimeWarning: divide by zero encountered in log2
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:26: RuntimeWarning: divide by zero encountered in log10


# **Aggregates & Outer products**

In [42]:
agg = np.random.randint(100,size=(10))
print('sum of the elements in the array = ',np.add.reduce(agg))
print('\n')
print('product of the elements in the array = ',np.multiply.reduce(agg))
print('\n')
print('running sum of the elements in the array = ',np.add.accumulate(agg))
print('\n')
#Outer products
np.multiply.outer(agg,agg)

sum of the elements in the array =  567


product of the elements in the array =  163720206041868000


running sum of the elements in the array =  [ 53 107 145 199 273 348 415 500 549 567]




array([[2809, 2862, 2014, 2862, 3922, 3975, 3551, 4505, 2597,  954],
       [2862, 2916, 2052, 2916, 3996, 4050, 3618, 4590, 2646,  972],
       [2014, 2052, 1444, 2052, 2812, 2850, 2546, 3230, 1862,  684],
       [2862, 2916, 2052, 2916, 3996, 4050, 3618, 4590, 2646,  972],
       [3922, 3996, 2812, 3996, 5476, 5550, 4958, 6290, 3626, 1332],
       [3975, 4050, 2850, 4050, 5550, 5625, 5025, 6375, 3675, 1350],
       [3551, 3618, 2546, 3618, 4958, 5025, 4489, 5695, 3283, 1206],
       [4505, 4590, 3230, 4590, 6290, 6375, 5695, 7225, 4165, 1530],
       [2597, 2646, 1862, 2646, 3626, 3675, 3283, 4165, 2401,  882],
       [ 954,  972,  684,  972, 1332, 1350, 1206, 1530,  882,  324]])

In [43]:
x = np.array([1,2,3])
print('confusion matrix','\n',np.multiply.outer(x,x))
print('\n')
print('running sum','\n',np.add.accumulate(x))

confusion matrix 
 [[1 2 3]
 [2 4 6]
 [3 6 9]]


running sum 
 [1 3 6]


In [44]:
agg2 = np.random.randint(100,size=(10))
print(np.min(agg2))
print(np.argmin(agg2))
print(np.max(agg2))
print(np.argmin(agg2))
print(np.argpartition(agg2,4))
print(np.std(agg2))
print(np.median(agg2))
print(np.percentile(agg2,25))
print(np.var(agg2))


0
0
97
0
[5 0 9 6 3 2 1 7 8 4]
30.710910113508522
49.5
31.0
943.1600000000001


# **Broadcaseting**

 Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

• Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

• Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is
raised.


In [45]:
#Broadcasting
import numpy as np 
a = np.arange(4)
b = np.random.randint(10,size = (4))
c = 10
d = np.random.randint(10,size = (4))[: , np.newaxis]
print('a: ',a)
print('b: ',b)
print('d: ','\n',d)
print('a+b = ',a+b)
print('a+c = ',a+c)
print('a+d = ','\n',a+d)


a:  [0 1 2 3]
b:  [9 5 7 2]
d:  
 [[2]
 [1]
 [4]
 [5]]
a+b =  [9 6 9 5]
a+c =  [10 11 12 13]
a+d =  
 [[2 3 4 5]
 [1 2 3 4]
 [4 5 6 7]
 [5 6 7 8]]


# Boolean **query**

In [46]:
#Boolean condition on array 
q = np.random.randint(100,size=(15))
print('q', q)
print('q>30: ',np.any(q>70))
print(q>70)
print(q[q>70])
print(q[q<30])
print(q[q==30])

q [70  5  3 98  0 65 76 79 37  2  3 47 67  2 89]
q>30:  True
[False False False  True False False  True  True False False False False
 False False  True]
[98 76 79 89]
[5 3 0 2 3 2]
[]


# **Sorting and Partitioning**

In [47]:
#numpy array sorting 
s = np.random.randint(100,size = (6))

In [48]:
print('Array: ',s)
print('Sorted array: ',np.sort(s))
print('Index sorted array: ',np.argsort(s))


Array:  [23 48 22 61 35 66]
Sorted array:  [22 23 35 48 61 66]
Index sorted array:  [2 0 4 1 3 5]


In [49]:
np.partition(s,2,axis=0)

array([22, 23, 35, 61, 48, 66])

In [50]:
s1 = np.random.randint(100,size=(3,3))
s1

array([[51, 31, 31],
       [20, 69, 93],
       [ 3, 25, 47]])

In [51]:
np.partition(s1,1,axis=0)

array([[ 3, 25, 31],
       [20, 31, 47],
       [51, 69, 93]])

In [52]:
np.partition(s1,1,axis=1)

array([[31, 31, 51],
       [20, 69, 93],
       [ 3, 25, 47]])