# 1.Create a Numpy 2D array using python range function and a for loop.


In [128]:
test_2d = np.array([range(i, i + 3) for i in [2, 4]])
print(test_2d)

[[2 3 4]
 [4 5 6]]


# 2. Convert the array created in question 3 and 4 of assignment 3 into an array of shape 2 rows and 5 columns.


In [2]:
import numpy as np

In [5]:
arr1=np.arange(10,dtype=int).reshape(2,5)
print(arr1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
arr2=np.linspace(0,9,10,dtype=int).reshape(2,5)
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


# 3.Create a Numpy array of shape 4x5. The numbers are generated randomly from a uniform distribution.The values of the numbers are between 1 to 100.


In [40]:
arr3=np.random.uniform(1,100,(4,5)).reshape(4,5)
print(arr3)

[[25.29769406 16.96877686 37.20705595 55.17371088 47.12259866]
 [26.53834285  8.12641975 91.46462882 62.76492122 18.84330158]
 [21.50760238 34.84583094 23.63335366 11.43614042 71.91813486]
 [27.91225973 64.52972394 11.80724524 69.10716628 88.89975597]]


# 4.Create a Numpy array of shape 4x5. The numbers are generated randomly from a normal distribution. The mean and variance of the normal distribution will be 0 and 1 respectively.


In [62]:
arr4=np.random.normal(0,1,(4,5))
arr4

array([[ 1.97435196, -1.17876968,  0.56956719,  0.10430088, -0.61610412],
       [-0.33771555, -0.1991537 , -0.32215536,  0.91529432, -0.21746123],
       [ 1.32969152, -0.21341972,  0.42502356, -0.22070671,  0.45793141],
       [ 1.72482088,  0.48112697, -0.38258309,  0.38170307,  1.06495012]])

# 5. Create a Numpy array of shape 4x5 having integer values. The numbers are generated randomly from a normal distribution. The mean and variance of the normal distribution will be 0 and 1 respectively.

In [23]:
np.random.normal(0,1,(4,5))


array([[-0.75293286, -0.91209005,  1.04238407,  0.59798502,  1.87138527],
       [ 1.00442983,  0.4628939 ,  0.47003341,  0.46958795,  0.31210656],
       [-0.68584998,  0.43284633,  0.66559416,  1.21605312, -1.15491142],
       [-0.92620986, -0.74251699, -0.61562079, -0.6945908 ,  0.64433028]])

# 6.Print the size, shape, and the dimension of the array you have created in question 3.

In [27]:
print("Size of the array is :",np.size(arr3))
print("Shape of the array is :",np.shape(arr3))
print("dimension of the array is :",np.ndim(arr3))

Size of the array is : 20
Shape of the array is : (20,)
dimension of the array is : 1


# 7.Print the data type, the size of each array element, and the total size of the array you have created in question 3.

In [28]:
print("Data type  of the array is :",arr3.dtype)
print("Size of the array is :",arr3.itemsize)
print("Size of the array is :",arr3.nbytes)

Data type  of the array is : float64
Size of the array is : 8
Size of the array is : 160


# 8.Print the element located at 2nd row and 3rd column in the array created in 3.

In [51]:
arr3[1:2,2]


array([91.46462882])

# 9.Print the same element mentioning the index using negative numbers.

In [60]:
arr3[-3:-2,-3:-2]


array([[91.46462882]])

# 10. Change the value of the same element to 12.

In [61]:
arr3[1:2,2]=12
arr3

array([[25.29769406, 16.96877686, 37.20705595, 55.17371088, 47.12259866],
       [26.53834285,  8.12641975, 12.        , 62.76492122, 18.84330158],
       [21.50760238, 34.84583094, 23.63335366, 11.43614042, 71.91813486],
       [27.91225973, 64.52972394, 11.80724524, 69.10716628, 88.89975597]])

# 11.Print the 2nd and 3rd row and 2nd and 3rd column from the Numpy array created in 4.


In [129]:
row34=arr4[1:3]
print(row34)

[[-0.33771555 -0.1991537  -0.32215536  0.91529432 -0.21746123]
 [ 1.32969152 -0.21341972  0.42502356 -0.22070671  0.45793141]]


In [130]:
col34=arr4[:,1:3]
col34

array([[-1.17876968,  0.56956719],
       [-0.1991537 , -0.32215536],
       [-0.21341972,  0.42502356],
       [ 0.48112697, -0.38258309]])

In [67]:
#intersection of 2 & 3 row and 2 & 3 olumn 
row_col34=arr4[1:3,1:3]
print(row_col34)

array([[-0.1991537 , -0.32215536],
       [-0.21341972,  0.42502356]])

# 12. Print every other row and every other column from 2nd row and 2nd column from the Numpy array created in question 4.

In [70]:
#Every other row starting form index 1
arr4[1::2]

array([[-0.33771555, -0.1991537 , -0.32215536,  0.91529432, -0.21746123],
       [ 1.72482088,  0.48112697, -0.38258309,  0.38170307,  1.06495012]])

In [72]:
#Every other row starting form index 0
arr4[::2]

array([[ 1.97435196, -1.17876968,  0.56956719,  0.10430088, -0.61610412],
       [ 1.32969152, -0.21341972,  0.42502356, -0.22070671,  0.45793141]])

# 13. Print the 2nd and 3rd row and 2nd and 3rd column in reverse order from the Numpy array created in 4.

In [73]:
#Reverse 2nd & 3rd  row in reverse 
np.fliplr(arr4[1:3])

array([[-0.21746123,  0.91529432, -0.32215536, -0.1991537 , -0.33771555],
       [ 0.45793141, -0.22070671,  0.42502356, -0.21341972,  1.32969152]])

In [74]:
#Reverse 2nd & 3rd  column in reverse 
np.fliplr(arr4[:,1:3])

array([[ 0.56956719, -1.17876968],
       [-0.32215536, -0.1991537 ],
       [ 0.42502356, -0.21341972],
       [-0.38258309,  0.48112697]])

In [75]:
#flip the intersection of 2nd  and 3rd row &column
np.fliplr(arr4[1:3,1:3])

array([[-0.32215536, -0.1991537 ],
       [ 0.42502356, -0.21341972]])

# 14. Concatenate the arrays from question 3 and 4 row-wise and column wise

In [84]:
#concatenate column  wise using concatenate 
np.concatenate((arr3,arr4),axis=1)

array([[25.29769406, 16.96877686, 37.20705595, 55.17371088, 47.12259866,
         1.97435196, -1.17876968,  0.56956719,  0.10430088, -0.61610412],
       [26.53834285,  8.12641975, 12.        , 62.76492122, 18.84330158,
        -0.33771555, -0.1991537 , -0.32215536,  0.91529432, -0.21746123],
       [21.50760238, 34.84583094, 23.63335366, 11.43614042, 71.91813486,
         1.32969152, -0.21341972,  0.42502356, -0.22070671,  0.45793141],
       [27.91225973, 64.52972394, 11.80724524, 69.10716628, 88.89975597,
         1.72482088,  0.48112697, -0.38258309,  0.38170307,  1.06495012]])

In [86]:
#concatenate row wise using contcatenate 
np.concatenate((arr3,arr4),axis=0)

array([[25.29769406, 16.96877686, 37.20705595, 55.17371088, 47.12259866],
       [26.53834285,  8.12641975, 12.        , 62.76492122, 18.84330158],
       [21.50760238, 34.84583094, 23.63335366, 11.43614042, 71.91813486],
       [27.91225973, 64.52972394, 11.80724524, 69.10716628, 88.89975597],
       [ 1.97435196, -1.17876968,  0.56956719,  0.10430088, -0.61610412],
       [-0.33771555, -0.1991537 , -0.32215536,  0.91529432, -0.21746123],
       [ 1.32969152, -0.21341972,  0.42502356, -0.22070671,  0.45793141],
       [ 1.72482088,  0.48112697, -0.38258309,  0.38170307,  1.06495012]])

In [80]:
#concatenate row wise using vstack 
np.vstack((arr3,arr4))

array([[25.29769406, 16.96877686, 37.20705595, 55.17371088, 47.12259866],
       [26.53834285,  8.12641975, 12.        , 62.76492122, 18.84330158],
       [21.50760238, 34.84583094, 23.63335366, 11.43614042, 71.91813486],
       [27.91225973, 64.52972394, 11.80724524, 69.10716628, 88.89975597],
       [ 1.97435196, -1.17876968,  0.56956719,  0.10430088, -0.61610412],
       [-0.33771555, -0.1991537 , -0.32215536,  0.91529432, -0.21746123],
       [ 1.32969152, -0.21341972,  0.42502356, -0.22070671,  0.45793141],
       [ 1.72482088,  0.48112697, -0.38258309,  0.38170307,  1.06495012]])

In [81]:
##concatenate column wise using hstack 
np.hstack((arr3,arr4))

array([[25.29769406, 16.96877686, 37.20705595, 55.17371088, 47.12259866,
         1.97435196, -1.17876968,  0.56956719,  0.10430088, -0.61610412],
       [26.53834285,  8.12641975, 12.        , 62.76492122, 18.84330158,
        -0.33771555, -0.1991537 , -0.32215536,  0.91529432, -0.21746123],
       [21.50760238, 34.84583094, 23.63335366, 11.43614042, 71.91813486,
         1.32969152, -0.21341972,  0.42502356, -0.22070671,  0.45793141],
       [27.91225973, 64.52972394, 11.80724524, 69.10716628, 88.89975597,
         1.72482088,  0.48112697, -0.38258309,  0.38170307,  1.06495012]])

# 15.Create a 1D array of size 5 and a 2D array of shape 4x5. Stack them vertically and horizontally.

In [96]:
test1=np.random.randint(1,50,(1,5))
test1
test3=np.random.randint(1,50,(5,1))

In [91]:
test2=np.random.randint(1,50,(4,5))
test2

array([[34, 34, 43,  2, 11],
       [15, 12, 36, 47,  8],
       [40, 28, 17, 45, 27],
       [24, 39, 40, 27,  5]])

In [100]:
test3=np.random.randint(1,50,(4,1))
test3

array([[33],
       [39],
       [34],
       [11]])

In [93]:
#stack vertically
np.vstack((test1,test2))

array([[11,  9, 18, 19,  4],
       [34, 34, 43,  2, 11],
       [15, 12, 36, 47,  8],
       [40, 28, 17, 45, 27],
       [24, 39, 40, 27,  5]])

1D array of size 5 can stack top of the 4X5 array , but can't be stack horizonatally because the for 4X5 matrix,5 row is present . Hence there is a dimensional mismatch 

In [101]:
#stack horizontally
np.hstack((test2,test3))

array([[34, 34, 43,  2, 11, 33],
       [15, 12, 36, 47,  8, 39],
       [40, 28, 17, 45, 27, 34],
       [24, 39, 40, 27,  5, 11]])

# 16. Get the 2D array from question 4 and split it vertically and horizontally in 3 parts.

In [124]:
np.vsplit(arr4, [1,2])

[array([[ 1.97435196, -1.17876968,  0.56956719,  0.10430088, -0.61610412]]),
 array([[-0.33771555, -0.1991537 , -0.32215536,  0.91529432, -0.21746123]]),
 array([[ 1.32969152, -0.21341972,  0.42502356, -0.22070671,  0.45793141],
        [ 1.72482088,  0.48112697, -0.38258309,  0.38170307,  1.06495012]])]

In [125]:
np.hsplit(arr4, [1,2])

[array([[ 1.97435196],
        [-0.33771555],
        [ 1.32969152],
        [ 1.72482088]]),
 array([[-1.17876968],
        [-0.1991537 ],
        [-0.21341972],
        [ 0.48112697]]),
 array([[ 0.56956719,  0.10430088, -0.61610412],
        [-0.32215536,  0.91529432, -0.21746123],
        [ 0.42502356, -0.22070671,  0.45793141],
        [-0.38258309,  0.38170307,  1.06495012]])]