<a href="https://colab.research.google.com/github/RSeth-Creator/Data/blob/dataScience/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Pandas** 

In [9]:
import pandas as pd 
import numpy as np 

# **Pandas series object**

In [10]:
ds1 = pd.Series([1,2,3,4])
print('series with default index :')
ds1


series with default index :


0    1
1    2
2    3
3    4
dtype: int64

In [11]:
ds2 = pd.Series([1,2,3,4],index=[1,2,3,4])
print('series with default index :')
ds2

series with default index :


1    1
2    2
3    3
4    4
dtype: int64

In [12]:
ds3 = pd.Series([1,2,3,4],index=['a','b','c','d'])
print('series with default index :')
ds3

series with default index :


a    1
b    2
c    3
d    4
dtype: int64

In [13]:
ds4 = pd.Series(10,index=[1,2,3,4])
print('series with default index :')
ds4

series with default index :


1    10
2    10
3    10
4    10
dtype: int64

In [14]:
ds5 = pd.Series('a',index=[1,2,3,4])
print('series with default index :')
ds5

series with default index :


1    a
2    a
3    a
4    a
dtype: object

In [15]:
print(ds3.values)
print('\n')
print(ds3['b'])

[1 2 3 4]


2


In [16]:
 population_dict = {'California': 38332521,
 'Texas': 26448193,
 'New York': 19651127,
 'Florida': 19552860,
 'Illinois': 12882135}
 population = pd.Series(population_dict)


In [17]:
population['Florida':'Illinois']

Florida     19552860
Illinois    12882135
dtype: int64

# **pandas DataFrame Objects**

In [18]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
 'Florida': 170312, 'Illinois': 149995}

In [19]:
 states = pd.DataFrame({'population': population})
 states

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [20]:
s1 = pd.DataFrame(area_dict,index = ['Population'])
s1

California   Texas  New York  Florida  Illinois
Population      423967  695662    141297   170312    149995

In [21]:
s2 = pd.DataFrame(np.random.randint(100,size=(5,3)),columns = ['a','b','c'],index = [1,2,3,4,5])
s2

a   b   c
1  27  97  24
2  39  99  58
3  56  50  77
4  13  82   6
5  88  75  95

In [22]:
ind_data = pd.DataFrame(np.random.randint(100,size=(5,3)),columns = ['a','b','c'],index = [1,2,3,4,5])


In [23]:
print(ind_data[1:3])
print('\n')
print(ind_data['a'])
print('\n')
print(ind_data>5)
print((ind_data>50) & (ind_data<70))


    a   b   c
2  64  65  52
3  48  60  15


1    59
2    64
3    48
4    68
5    39
Name: a, dtype: int64


      a     b     c
1  True  True  True
2  True  True  True
3  True  True  True
4  True  True  True
5  True  True  True
       a      b      c
1   True  False  False
2   True   True   True
3  False   True  False
4   True  False  False
5  False  False  False


In [24]:
print(ind_data)
print('\n')
#data location Provided index
print(ind_data.loc[1])
print(ind_data.loc[1:3])
print('\n')
#index location inbuilt index
print(ind_data.iloc[1])
print('\n')
print(ind_data.iloc[1:3])

    a   b   c
1  59  16  30
2  64  65  52
3  48  60  15
4  68  18  87
5  39  79  78


a    59
b    16
c    30
Name: 1, dtype: int64
    a   b   c
1  59  16  30
2  64  65  52
3  48  60  15


a    64
b    65
c    52
Name: 2, dtype: int64


    a   b   c
2  64  65  52
3  48  60  15


# **Data Selection and operations in DataFrame**

In [25]:
 area = pd.Series({'California': 423967, 'Texas': 695662,
 'New York': 141297, 'Florida': 170312,
 'Illinois': 149995})
 pop = pd.Series({'California': 38332521, 'Texas': 26448193,
 'New York': 19651127, 'Florida': 19552860,
 'Illinois': 12882135})
 data = pd.DataFrame({'area':area, 'pop':pop})
 data


area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [26]:
print(data['area'])
print('\n')
print(data['pop'])
print('\n')

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64


California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: pop, dtype: int64




In [27]:
print( data['Florida':'Illinois'])
print('\n')
print(data.area['Florida'])

            area       pop
Florida   170312  19552860
Illinois  149995  12882135


170312


In [28]:
data['dens']=  data['pop']/data['area']
data['dens_norm'] = (data['dens'] - np.max(data['dens']))/(np.max(data['dens'])-np.min(data['dens']))
data

area       pop        dens  dens_norm
California  423967  38332521   90.413926  -0.481534
Texas       695662  26448193   38.018740  -1.000000
New York    141297  19651127  139.076746   0.000000
Florida     170312  19552860  114.806121  -0.240165
Illinois    149995  12882135   85.883763  -0.526361

In [29]:
data.T

California         Texas      New York       Florida      Illinois
area       4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop        3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
dens       9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01
dens_norm -4.815335e-01 -1.000000e+00  0.000000e+00 -2.401653e-01 -5.263609e-01

In [30]:
data.loc[(data.dens>100),['area','pop']]

area       pop
New York  141297  19651127
Florida   170312  19552860

In [31]:
 df = pd.DataFrame([[1, np.nan, 2], [2, 3, 5], [np.nan, 4, 6]])

In [32]:
df.isnull()

0      1      2
0  False   True  False
1  False  False  False
2   True  False  False

In [33]:
#df.dropna()
df.fillna(method='ffill')
df.fillna(method='bfill')

0    1  2
0  1.0  3.0  2
1  2.0  3.0  5
2  NaN  4.0  6

# **Combinig Dataset Concate & Append**

In [34]:
import numpy as np 
import pandas as pd 
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
print(np.concatenate([x,y,z]))
print('\n')
print(np.vstack([x,y,z]))

[1 2 3 4 5 6 7 8 9]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
 x = [[1, 2], [3, 4]]
 print(np.concatenate([x,x],axis = 0))
 print('\n')
 print(np.concatenate([x,x],axis = 1))


[[1 2]
 [3 4]
 [1 2]
 [3 4]]


[[1 2 1 2]
 [3 4 3 4]]


In [36]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])
pd.concat([ser1,ser2],axis = 0)


1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [37]:
pd.concat([ser1,ser2],axis=1)

0    1
1    A  NaN
2    B  NaN
3    C  NaN
4  NaN    D
5  NaN    E
6  NaN    F

In [38]:
ser1 = pd.Series(['A', 'B', 'C'], index=[1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index=[2, 3, 4])

In [39]:
pd.concat([ser1,ser2],axis = 1)

0    1
1    A  NaN
2    B    D
3    C    E
4  NaN    F

In [40]:
pd.concat([ser1,ser2],keys = ['ser1','ser2'])

ser1  1    A
      2    B
      3    C
ser2  2    D
      3    E
      4    F
dtype: object

In [41]:
pd.concat([ser1,ser2],join = 'inner')

1    A
2    B
3    C
2    D
3    E
4    F
dtype: object

In [42]:
pd.concat([ser1,ser2],join = 'outer')

1    A
2    B
3    C
2    D
3    E
4    F
dtype: object

In [43]:
ser1.append(ser2)

1    A
2    B
3    C
2    D
3    E
4    F
dtype: object

In [44]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
 'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
 'hire_date': [2004, 2008, 2012, 2014]})

In [45]:
df1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [46]:
df2

employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

# **Merge, Join & Pivot Table**

In [52]:
df3 = pd.merge(df1,df2,how='left')

In [48]:
pd.merge(df1,df2,how='inner')

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [93]:
df3.query('hire_date>2008')

employee        group  hire_date
1     Jake  Engineering       2012
3      Sue           HR       2014

In [94]:
df3.query("employee == 'Bob'")

employee       group  hire_date
0      Bob  Accounting       2008

In [50]:
pd.merge(df1,df2,how='right',on ='employee')

employee        group  hire_date
0     Lisa  Engineering       2004
1      Bob   Accounting       2008
2     Jake  Engineering       2012
3      Sue           HR       2014

In [51]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
 'supervisor': ['Carly', 'Guido', 'Steve']})

In [53]:
df4

group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

In [55]:
pd.merge(df3,df4,how='left',left_on='group',right_on='group')

employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [57]:
df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
 'data': range(6)}, columns=['key', 'data'])


In [58]:
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [64]:
df.groupby('key').sum()

data
key      
A       3
B       5
C       7

In [65]:
df.groupby('key').sum().describe()

data
count   3.0
mean    5.0
std     2.0
min     3.0
25%     4.0
50%     5.0
75%     6.0
max     7.0

In [66]:
df.groupby('key').sum().describe().unstack()

data  count    3.0
      mean     5.0
      std      2.0
      min      3.0
      25%      4.0
      50%      5.0
      75%      6.0
      max      7.0
dtype: float64

In [67]:
 rng = np.random.RandomState(0)
 df = pd.DataFrame({'key': ['A', 'B', 'C', 'A', 'B', 'C'],
 'data1': range(6),
 'data2': rng.randint(0, 10, 6)},
 columns = ['key', 'data1', 'data2'])


In [68]:
df

key  data1  data2
0   A      0      5
1   B      1      0
2   C      2      3
3   A      3      3
4   B      4      7
5   C      5      9

In [69]:
df.groupby('key').sum().describe().unstack()

data1  count     3.000000
       mean      5.000000
       std       2.000000
       min       3.000000
       25%       4.000000
       50%       5.000000
       75%       6.000000
       max       7.000000
data2  count     3.000000
       mean      9.000000
       std       2.645751
       min       7.000000
       25%       7.500000
       50%       8.000000
       75%      10.000000
       max      12.000000
dtype: float64

In [71]:
df.groupby('key').aggregate([min,max,np.mean])

data1          data2         
      min max mean   min max mean
key                              
A       0   3  1.5     3   5  4.0
B       1   4  2.5     0   7  3.5
C       2   5  3.5     3   9  6.0

In [75]:
df.groupby('key').transform(lambda x: x - x.mean())


data1  data2
0   -1.5    1.0
1   -1.5   -3.5
2   -1.5   -3.0
3    1.5   -1.0
4    1.5    3.5
5    1.5    3.0

In [76]:
df.T

0  1  2  3  4  5
key    A  B  C  A  B  C
data1  0  1  2  3  4  5
data2  5  0  3  3  7  9

In [86]:

x1 = pd.qcut(df['data1'], 2)
x1

0    (-0.001, 2.5]
1    (-0.001, 2.5]
2    (-0.001, 2.5]
3       (2.5, 5.0]
4       (2.5, 5.0]
5       (2.5, 5.0]
Name: data1, dtype: category
Categories (2, interval[float64]): [(-0.001, 2.5] < (2.5, 5.0]]

In [90]:
pd.pivot_table(df,index='data1',columns='key', aggfunc='mean')

data2          
key       A    B    C
data1                
0       5.0  NaN  NaN
1       NaN  0.0  NaN
2       NaN  NaN  3.0
3       3.0  NaN  NaN
4       NaN  7.0  NaN
5       NaN  NaN  9.0