In [1]:
import numpy as np 
import pandas as pd 

In [40]:
#1) Create a Pandas Series from a list or array which contains 0:25, 0:5, 0:75, and 1:0.
l = [0.25, 0.5, 0.75, 1.0]
#i = ['a','b','c','d']
ps = pd.Series(l)
ps

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [41]:
#2)Access the values and indices of the series separately and print it.
#print indices seperately
#1)
for row in ps.index: 
    print(row, end = " ") 
print('\n')
#2)
ind = list(ps.index.values)
print('indices of the series is' , ind)
print('\n')

#Print values seperately
values = ps.tolist()
print('Values of the series is' , values)


0 1 2 3 

indices of the series is [0, 1, 2, 3]


Values of the series is [0.25, 0.5, 0.75, 1.0]


In [42]:
#3)Access the 2nd and 3rd data from Series using Numpy array square bracket notation.
ele = ps[1:3]
ele
print('The 2nd and 3rd data from Series is  - ',ele.tolist())



The 2nd and 3rd data from Series is  -  [0.5, 0.75]


In [44]:
#4) Create the same series having the same values but dierent indices as a, b, c,and d.
l = [0.25, 0.5, 0.75, 1.0]
i = ['a','b','c','d']
psn = pd.Series(l, index=i)
psn

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [49]:
#5)How do you access the data at index b.
psn['b']
print('\n')
print('data at index b is :',  psn['b'])



data at index b is : 0.5


In [53]:
#6)Give an example of non-contiguous or non-sequential indices.
nc = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
print('example non-contiguous or non-sequential indices','\n',nc)


example non-contiguous or non-sequential indices 
 2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64


In [54]:
'''7)Create a python dictionary named population dict with the following key-value
pairs:
California - 38332521
Texas - 26448193
New York - 19651127
Florida - 19552860
Illinois - 12882135'''

'7)Create a python dictionary named population dict with the following key-value\npairs:\nCalifornia - 38332521\nTexas - 26448193\nNew York - 19651127\nFlorida - 19552860\nIllinois - 12882135'

In [59]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population_dict

{'California': 38332521,
 'Texas': 26448193,
 'New York': 19651127,
 'Florida': 19552860,
 'Illinois': 12882135}

In [66]:
#8)Create a series from the above dictionary.
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [61]:
#9)Extract the population of California from the above created series.
pop_cal = population['California']
print('population of California is : ',pop_cal)

population of California is :  38332521


In [64]:
#10)Extract the population from California to Illinois using Numpy array square bracket notation.
pop = population['California':'Illinois']
print('population of California to Illinois is : ','\n',pop)

population of California to Illinois is :  
 California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64


In [ ]:
#11)Is series index an optional argument? If yes, give an example and mention what is it's default values.
Index is an optional argument  as we know the syntax for the pandas dataframe : dataframe = pd.series(data,index = index ) . If no external index is provided then  it will start from 0 and act as auto increment key with increment of 1 .

In [68]:
#example (No external index provided) :
df = pd.Series(['a','b','c','d'])
df

0    a
1    b
2    c
3    d
dtype: object

In [69]:
#example ( external index provided) :
df = pd.Series(['a','b','c','d'], index = ['a1','b1','c1','d1'])
df

a1    a
b1    b
c1    c
d1    d
dtype: object

In [72]:
#12)Create a series of 4 data when each data is equal or same and four indices are different.
df_1 = pd.Series('a', index=[1,2,3,4,5])
df_1


1    a
2    a
3    a
4    a
5    a
dtype: object

In [73]:
df_2 = pd.Series(1, index=[1,2,3,4,5])
df_2

1    1
2    1
3    1
4    1
5    1
dtype: int64

In [75]:
#13)Which function is used to split the entire dataset into training and test data.


In [ ]:
#14

In [80]:
#15) How do you concatenate two one dimensional array in Numpy. Give an example.
#We can use concatenate function two concatenate twoone dimensional array :np.concatenate([arr1,arr2])
a = np.array([1, 2, 3])
b = np.array([4, 5])
r= np.concatenate([a,b])
print ( 'final array after concatenation is : ', r)

final array after concatenation is :  [1 2 3 4 5]


In [86]:
#16) Calculate the sum and product of 5 numbers using numpy reduce method. 
import functools  
ls = np.random.randint(1,10, size=5)
print (' the ist is :',ls)
# using reduce to compute sum of list 
print ("The sum of the list elements is : ",end="") 
print (functools.reduce(lambda a,b : a+b,ls)) 

# using reduce to compute product  of list 
print ("The sum of the list elements is : ",end="") 
print (functools.reduce(lambda a,b : a*b,ls)) 

 the ist is : [8 4 1 2 2]
The sum of the list elements is : 17
The sum of the list elements is : 128


In [93]:
#17)Which function would you use if you would like to get all the intermediate results of sum of 5 numbers in an array. Give an example. 
# Example: input: 1, 2, 3, 4, 5, output: 1, 3, 6, 10, 15

#to get all the intermediate results of sum of n numbers we will use np.cumsum(list_name) 
# Given list 
a= [1, 2, 3, 4, 5]
r = np.cumsum(a)
r

array([ 1,  3,  6, 10, 15], dtype=int32)

In [145]:
#18)What will be the result of M + a where M = np.ones(3, 2), and a = np.arange(3) and what is the reason of the outcome?
M = np.ones((3, 2), dtype=float)
print(M)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [146]:
a = np.arange(3)



In [147]:
M+a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [148]:

#resolutoion
a = np.arange(3)[:, np.newaxis]

In [149]:
M+a

array([[1., 1.],
       [2., 2.],
       [3., 3.]])