In [1]:
import numpy as np 

1.Create a list of integers from 0 to 9 using the function range

In [7]:
l=list(range(0,10))
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


2.Create a Numpy 1D array from a python list created in question 1.

In [16]:
arr=np.array(l,dtype=int)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


3.Create the same numpy array as in question 2 using Numpy arange() function.

In [20]:
arr1=np.arange(10,dtype=int)
print(arr1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

4.Create the same numpy array as in question 2 using Numpy linspace() function.

In [29]:
arr2=np.linspace(0,9,9,dtype=int)
print(arr2)

array([0, 1, 2, 3, 4, 5, 6, 7, 9])

5.Create a Numpy array of size 10. The numbers are generated randomly from a uniform distribution. 
The values of the numbers are between 1 to 100.

In [49]:
arr3=np.random.uniform(1,100,size=(10))
print(arr3)

[66.39329295 51.50613684 66.74532374 31.08533762 57.1028597  15.00198801
 11.19250444 39.41049533 29.45100703 22.67518778]


6.Create a Numpy array of size 10. The numbers are generated randomly from a normal distribution.
The mean and variance of the normal distribution will be 0 and 1 respectively.


In [50]:
arr4=np.random.normal(0,1, size=(10))
print(arr4)

[ 2.65015114  0.92220336  0.58247665  0.97988197 -0.48042978  2.13641459
 -0.8703333  -0.09458002  0.27847631 -0.09381504]


7.Print the size, shape, and the dimension of the array you have created in question 6.


In [51]:
print("Size of the array is :",np.size(arr4))
print("Shape of the array is :",np.shape(arr4))
print("dimension of the array is :",np.ndim(arr4))

Size of the array is : 10
Shape of the array is : (10,)
dimension of the array is : 1


8.Print the data type, the size of each array element, and the total size of the array you have created in question 6.


In [120]:
print("Data type  of the array is :",arr4.dtype)
print("Size of the array is :",arr4.itemsize)
print("Size of the array is :",arr4.nbytes)

Data type  of the array is : float64
Size of the array is : 8
Size of the array is : 80


9.Print the first and fifth element of the array you have created in question 6.


In [64]:
 print("first and fifth element of the array are:",arr4[0],arr4[4])

first and fifth element of the array are: 2.6501511423085344 -0.48042977841543266


10.Print the first and fifth elements of the array using negative indices for the array you have created in question 6.

In [74]:
print("the first element is :",arr4[-len(arr4)])
print(" the fifth element is :" ,arr4[-(int(len(arr4)/2)+1)])

the first element is : 2.6501511423085344
 the fifth element is : -0.48042977841543266


11.Change the value of the sixth element to 50.


In [121]:
arr4[5]=50
arr4[5]

50.0

12.Print the first five elements of the array using slicing notation.

In [81]:
print("First five elements of the array using slicing , are :",arr4[0:5])

First five elements of the array using slicing , are : [ 2.65015114  0.92220336  0.58247665  0.97988197 -0.48042978]


13.Print the elements after index 5.

In [85]:
print("The elements after index 5 are:",arr4[6:])

The elements after index 5 are: [-0.8703333  -0.09458002  0.27847631 -0.09381504]


14.Print the elements between 4th index and 7th index.


In [87]:
print("the elements between 4th and 7th index are:", arr4[4:7])

the elements between 4th and 7th index are: [-0.48042978 50.         -0.8703333 ]


15.Print every other element.


In [94]:
print("Every other elements are:", arr4[::2])
print("Every other elements starting at index 1 are:", arr4[1::2])


Every other elements are: [ 2.65015114  0.58247665 -0.48042978 -0.8703333   0.27847631]
Every other elements are: [ 0.92220336  0.97988197 50.         -0.09458002 -0.09381504]


16.Print every other element from index 4 to index 7.


In [96]:
print("Every other element from index 4 to index7 is :", arr4[4::7])

Every other element from index 4 to index7 is : [-0.48042978]


17.Print every element, every other element, and every other element from index 4 to index 7 reversed.

In [107]:
print("Every element in reverse are :",arr4[::-1])


Every element in reverse are : [-0.09381504  0.27847631 -0.09458002 -0.8703333  50.         -0.48042978
  0.97988197  0.58247665  0.92220336  2.65015114]


In [109]:
#using flip function
arr5=np.flip(arr4)
arr5


array([-0.09381504,  0.27847631, -0.09458002, -0.8703333 , 50.        ,
       -0.48042978,  0.97988197,  0.58247665,  0.92220336,  2.65015114])

In [110]:
print("every other elements in reverse order are :",arr5[::2])

array([-0.09381504, -0.09458002, 50.        ,  0.97988197,  0.92220336])

In [111]:
print("every other element from index 4 to index 7 reversed are:",arr5[4::7])

every other element from index 4 to index 7 reversed are: [50.]


18.Concatenate the arrays created in question 2, 3, 4, 5, and 6

In [115]:
np.concatenate([arr,arr1,arr2,arr3,arr4])

array([ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ,
        5.        ,  6.        ,  7.        ,  8.        ,  9.        ,
        0.        ,  1.        ,  2.        ,  3.        ,  4.        ,
        5.        ,  6.        ,  7.        ,  8.        ,  9.        ,
        0.        ,  1.        ,  2.        ,  3.        ,  4.        ,
        5.        ,  6.        ,  7.        ,  9.        , 66.39329295,
       51.50613684, 66.74532374, 31.08533762, 57.1028597 , 15.00198801,
       11.19250444, 39.41049533, 29.45100703, 22.67518778,  2.65015114,
        0.92220336,  0.58247665,  0.97988197, -0.48042978, 50.        ,
       -0.8703333 , -0.09458002,  0.27847631, -0.09381504])

19.Split the array in question 6 into 5 parts by cutting it at index 2, 4, 6 and 8.

In [117]:
p1,p2,p3,p4,p5=np.split(arr4,[2,4,6,8])
print(p1,p2,p3,p4,p5)

[2.65015114 0.92220336] [0.58247665 0.97988197] [-0.48042978 50.        ] [-0.8703333  -0.09458002] [ 0.27847631 -0.09381504]
